//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacionAvanzada.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BD_LENEntities : DbContext
    {
        public BD_LENEntities()
            : base("name=BD_LENEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_canton> TB_canton { get; set; }
        public virtual DbSet<TB_carrito> TB_carrito { get; set; }
        public virtual DbSet<TB_categoria> TB_categoria { get; set; }
        public virtual DbSet<TB_detalle_carrito> TB_detalle_carrito { get; set; }
        public virtual DbSet<TB_detalle_pedido> TB_detalle_pedido { get; set; }
        public virtual DbSet<TB_direccion_envio> TB_direccion_envio { get; set; }
        public virtual DbSet<TB_distrito> TB_distrito { get; set; }
        public virtual DbSet<TB_error> TB_error { get; set; }
        public virtual DbSet<TB_estado> TB_estado { get; set; }
        public virtual DbSet<TB_factura> TB_factura { get; set; }
        public virtual DbSet<TB_imagen_producto> TB_imagen_producto { get; set; }
        public virtual DbSet<TB_metodo_pago> TB_metodo_pago { get; set; }
        public virtual DbSet<TB_pago> TB_pago { get; set; }
        public virtual DbSet<TB_pedido> TB_pedido { get; set; }
        public virtual DbSet<TB_producto> TB_producto { get; set; }
        public virtual DbSet<TB_provincia> TB_provincia { get; set; }
        public virtual DbSet<TB_rol> TB_rol { get; set; }
        public virtual DbSet<TB_usuario> TB_usuario { get; set; }
    
        public virtual ObjectResult<SP_ActualizarCantidadCarrito_Result> SP_ActualizarCantidadCarrito(Nullable<int> idUsuario, Nullable<int> idProducto, Nullable<int> cantidad)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("IdProducto", idProducto) :
                new ObjectParameter("IdProducto", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("Cantidad", cantidad) :
                new ObjectParameter("Cantidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ActualizarCantidadCarrito_Result>("SP_ActualizarCantidadCarrito", idUsuarioParameter, idProductoParameter, cantidadParameter);
        }
    
        public virtual ObjectResult<SP_ActualizarContrasennaTemporal_Result> SP_ActualizarContrasennaTemporal(Nullable<int> idUsuario, string contrasenna, Nullable<System.DateTime> vigenciaContrasennaTemporal)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var contrasennaParameter = contrasenna != null ?
                new ObjectParameter("Contrasenna", contrasenna) :
                new ObjectParameter("Contrasenna", typeof(string));
    
            var vigenciaContrasennaTemporalParameter = vigenciaContrasennaTemporal.HasValue ?
                new ObjectParameter("VigenciaContrasennaTemporal", vigenciaContrasennaTemporal) :
                new ObjectParameter("VigenciaContrasennaTemporal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ActualizarContrasennaTemporal_Result>("SP_ActualizarContrasennaTemporal", idUsuarioParameter, contrasennaParameter, vigenciaContrasennaTemporalParameter);
        }
    
        public virtual ObjectResult<SP_ActualizarDireccionUsuario_Result> SP_ActualizarDireccionUsuario(Nullable<int> idDireccion, Nullable<int> idUsuario, Nullable<int> idDistrito, string direccionExacta, string referencia, string telefonoContacto, string nombreDestinatario, Nullable<bool> esPrincipal)
        {
            var idDireccionParameter = idDireccion.HasValue ?
                new ObjectParameter("IdDireccion", idDireccion) :
                new ObjectParameter("IdDireccion", typeof(int));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var idDistritoParameter = idDistrito.HasValue ?
                new ObjectParameter("IdDistrito", idDistrito) :
                new ObjectParameter("IdDistrito", typeof(int));
    
            var direccionExactaParameter = direccionExacta != null ?
                new ObjectParameter("DireccionExacta", direccionExacta) :
                new ObjectParameter("DireccionExacta", typeof(string));
    
            var referenciaParameter = referencia != null ?
                new ObjectParameter("Referencia", referencia) :
                new ObjectParameter("Referencia", typeof(string));
    
            var telefonoContactoParameter = telefonoContacto != null ?
                new ObjectParameter("TelefonoContacto", telefonoContacto) :
                new ObjectParameter("TelefonoContacto", typeof(string));
    
            var nombreDestinatarioParameter = nombreDestinatario != null ?
                new ObjectParameter("NombreDestinatario", nombreDestinatario) :
                new ObjectParameter("NombreDestinatario", typeof(string));
    
            var esPrincipalParameter = esPrincipal.HasValue ?
                new ObjectParameter("EsPrincipal", esPrincipal) :
                new ObjectParameter("EsPrincipal", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ActualizarDireccionUsuario_Result>("SP_ActualizarDireccionUsuario", idDireccionParameter, idUsuarioParameter, idDistritoParameter, direccionExactaParameter, referenciaParameter, telefonoContactoParameter, nombreDestinatarioParameter, esPrincipalParameter);
        }
    
        public virtual ObjectResult<SP_ActualizarUsuario_Result> SP_ActualizarUsuario(Nullable<int> idUsuario, string nombre, string apellido, string cedula, string telefono, string email, Nullable<int> idRol, Nullable<int> idEstado)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var idRolParameter = idRol.HasValue ?
                new ObjectParameter("IdRol", idRol) :
                new ObjectParameter("IdRol", typeof(int));
    
            var idEstadoParameter = idEstado.HasValue ?
                new ObjectParameter("IdEstado", idEstado) :
                new ObjectParameter("IdEstado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ActualizarUsuario_Result>("SP_ActualizarUsuario", idUsuarioParameter, nombreParameter, apellidoParameter, cedulaParameter, telefonoParameter, emailParameter, idRolParameter, idEstadoParameter);
        }
    
        public virtual ObjectResult<SP_Admin_ActualizarCategoria_Result> SP_Admin_ActualizarCategoria(Nullable<int> idCategoria, string nombreCategoria, string descripcion)
        {
            var idCategoriaParameter = idCategoria.HasValue ?
                new ObjectParameter("IdCategoria", idCategoria) :
                new ObjectParameter("IdCategoria", typeof(int));
    
            var nombreCategoriaParameter = nombreCategoria != null ?
                new ObjectParameter("NombreCategoria", nombreCategoria) :
                new ObjectParameter("NombreCategoria", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Admin_ActualizarCategoria_Result>("SP_Admin_ActualizarCategoria", idCategoriaParameter, nombreCategoriaParameter, descripcionParameter);
        }
    
        public virtual ObjectResult<SP_Admin_ActualizarEstadoPedido_Result> SP_Admin_ActualizarEstadoPedido(Nullable<int> idPedido, Nullable<int> idEstadoNuevo, string motivoCancelacion)
        {
            var idPedidoParameter = idPedido.HasValue ?
                new ObjectParameter("IdPedido", idPedido) :
                new ObjectParameter("IdPedido", typeof(int));
    
            var idEstadoNuevoParameter = idEstadoNuevo.HasValue ?
                new ObjectParameter("IdEstadoNuevo", idEstadoNuevo) :
                new ObjectParameter("IdEstadoNuevo", typeof(int));
    
            var motivoCancelacionParameter = motivoCancelacion != null ?
                new ObjectParameter("MotivoCancelacion", motivoCancelacion) :
                new ObjectParameter("MotivoCancelacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Admin_ActualizarEstadoPedido_Result>("SP_Admin_ActualizarEstadoPedido", idPedidoParameter, idEstadoNuevoParameter, motivoCancelacionParameter);
        }
    
        public virtual ObjectResult<SP_Admin_ActualizarProducto_Result> SP_Admin_ActualizarProducto(Nullable<int> idProducto, string nombreProducto, string descripcion, Nullable<decimal> precio, Nullable<int> stock, Nullable<bool> esPiezaUnica, Nullable<bool> destacado, Nullable<int> idCategoria)
        {
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("IdProducto", idProducto) :
                new ObjectParameter("IdProducto", typeof(int));
    
            var nombreProductoParameter = nombreProducto != null ?
                new ObjectParameter("NombreProducto", nombreProducto) :
                new ObjectParameter("NombreProducto", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("Precio", precio) :
                new ObjectParameter("Precio", typeof(decimal));
    
            var stockParameter = stock.HasValue ?
                new ObjectParameter("Stock", stock) :
                new ObjectParameter("Stock", typeof(int));
    
            var esPiezaUnicaParameter = esPiezaUnica.HasValue ?
                new ObjectParameter("EsPiezaUnica", esPiezaUnica) :
                new ObjectParameter("EsPiezaUnica", typeof(bool));
    
            var destacadoParameter = destacado.HasValue ?
                new ObjectParameter("Destacado", destacado) :
                new ObjectParameter("Destacado", typeof(bool));
    
            var idCategoriaParameter = idCategoria.HasValue ?
                new ObjectParameter("IdCategoria", idCategoria) :
                new ObjectParameter("IdCategoria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Admin_ActualizarProducto_Result>("SP_Admin_ActualizarProducto", idProductoParameter, nombreProductoParameter, descripcionParameter, precioParameter, stockParameter, esPiezaUnicaParameter, destacadoParameter, idCategoriaParameter);
        }
    
        public virtual ObjectResult<SP_Admin_ActualizarStock_Result> SP_Admin_ActualizarStock(Nullable<int> idProducto, Nullable<int> stock)
        {
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("IdProducto", idProducto) :
                new ObjectParameter("IdProducto", typeof(int));
    
            var stockParameter = stock.HasValue ?
                new ObjectParameter("Stock", stock) :
                new ObjectParameter("Stock", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Admin_ActualizarStock_Result>("SP_Admin_ActualizarStock", idProductoParameter, stockParameter);
        }
    
        public virtual ObjectResult<SP_Admin_CambiarEstadoCategoria_Result> SP_Admin_CambiarEstadoCategoria(Nullable<int> idCategoria)
        {
            var idCategoriaParameter = idCategoria.HasValue ?
                new ObjectParameter("IdCategoria", idCategoria) :
                new ObjectParameter("IdCategoria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Admin_CambiarEstadoCategoria_Result>("SP_Admin_CambiarEstadoCategoria", idCategoriaParameter);
        }
    
        public virtual ObjectResult<SP_Admin_CambiarEstadoProducto_Result> SP_Admin_CambiarEstadoProducto(Nullable<int> idProducto)
        {
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("IdProducto", idProducto) :
                new ObjectParameter("IdProducto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Admin_CambiarEstadoProducto_Result>("SP_Admin_CambiarEstadoProducto", idProductoParameter);
        }
    
        public virtual ObjectResult<SP_Admin_ConsultarBajoStock_Result> SP_Admin_ConsultarBajoStock(Nullable<int> stockMinimo)
        {
            var stockMinimoParameter = stockMinimo.HasValue ?
                new ObjectParameter("StockMinimo", stockMinimo) :
                new ObjectParameter("StockMinimo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Admin_ConsultarBajoStock_Result>("SP_Admin_ConsultarBajoStock", stockMinimoParameter);
        }
    
        public virtual ObjectResult<SP_Admin_ConsultarCategorias_Result> SP_Admin_ConsultarCategorias()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Admin_ConsultarCategorias_Result>("SP_Admin_ConsultarCategorias");
        }
    
        public virtual ObjectResult<SP_Admin_ConsultarCategoriasActivas_Result> SP_Admin_ConsultarCategoriasActivas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Admin_ConsultarCategoriasActivas_Result>("SP_Admin_ConsultarCategoriasActivas");
        }
    
        public virtual ObjectResult<SP_Admin_ConsultarDetallePedido_Result> SP_Admin_ConsultarDetallePedido(Nullable<int> idPedido)
        {
            var idPedidoParameter = idPedido.HasValue ?
                new ObjectParameter("IdPedido", idPedido) :
                new ObjectParameter("IdPedido", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Admin_ConsultarDetallePedido_Result>("SP_Admin_ConsultarDetallePedido", idPedidoParameter);
        }
    
        public virtual ObjectResult<SP_Admin_ConsultarEstadosPedido_Result> SP_Admin_ConsultarEstadosPedido()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Admin_ConsultarEstadosPedido_Result>("SP_Admin_ConsultarEstadosPedido");
        }
    
        public virtual ObjectResult<SP_Admin_ConsultarImagenesProducto_Result> SP_Admin_ConsultarImagenesProducto(Nullable<int> idProducto)
        {
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("IdProducto", idProducto) :
                new ObjectParameter("IdProducto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Admin_ConsultarImagenesProducto_Result>("SP_Admin_ConsultarImagenesProducto", idProductoParameter);
        }
    
        public virtual ObjectResult<SP_Admin_ConsultarPedidos_Result> SP_Admin_ConsultarPedidos(string busqueda, Nullable<int> idEstado, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, Nullable<int> pagina, Nullable<int> tamanoPagina)
        {
            var busquedaParameter = busqueda != null ?
                new ObjectParameter("Busqueda", busqueda) :
                new ObjectParameter("Busqueda", typeof(string));
    
            var idEstadoParameter = idEstado.HasValue ?
                new ObjectParameter("IdEstado", idEstado) :
                new ObjectParameter("IdEstado", typeof(int));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var paginaParameter = pagina.HasValue ?
                new ObjectParameter("Pagina", pagina) :
                new ObjectParameter("Pagina", typeof(int));
    
            var tamanoPaginaParameter = tamanoPagina.HasValue ?
                new ObjectParameter("TamanoPagina", tamanoPagina) :
                new ObjectParameter("TamanoPagina", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Admin_ConsultarPedidos_Result>("SP_Admin_ConsultarPedidos", busquedaParameter, idEstadoParameter, fechaInicioParameter, fechaFinParameter, paginaParameter, tamanoPaginaParameter);
        }
    
        public virtual ObjectResult<SP_Admin_ConsultarProductoPorId_Result> SP_Admin_ConsultarProductoPorId(Nullable<int> idProducto)
        {
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("IdProducto", idProducto) :
                new ObjectParameter("IdProducto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Admin_ConsultarProductoPorId_Result>("SP_Admin_ConsultarProductoPorId", idProductoParameter);
        }
    
        public virtual ObjectResult<SP_Admin_ConsultarProductos_Result> SP_Admin_ConsultarProductos(string busqueda, Nullable<int> idCategoria, Nullable<int> pagina, Nullable<int> tamanoPagina)
        {
            var busquedaParameter = busqueda != null ?
                new ObjectParameter("Busqueda", busqueda) :
                new ObjectParameter("Busqueda", typeof(string));
    
            var idCategoriaParameter = idCategoria.HasValue ?
                new ObjectParameter("IdCategoria", idCategoria) :
                new ObjectParameter("IdCategoria", typeof(int));
    
            var paginaParameter = pagina.HasValue ?
                new ObjectParameter("Pagina", pagina) :
                new ObjectParameter("Pagina", typeof(int));
    
            var tamanoPaginaParameter = tamanoPagina.HasValue ?
                new ObjectParameter("TamanoPagina", tamanoPagina) :
                new ObjectParameter("TamanoPagina", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Admin_ConsultarProductos_Result>("SP_Admin_ConsultarProductos", busquedaParameter, idCategoriaParameter, paginaParameter, tamanoPaginaParameter);
        }
    
        public virtual ObjectResult<SP_Admin_EliminarImagenProducto_Result> SP_Admin_EliminarImagenProducto(Nullable<int> idImagen)
        {
            var idImagenParameter = idImagen.HasValue ?
                new ObjectParameter("IdImagen", idImagen) :
                new ObjectParameter("IdImagen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Admin_EliminarImagenProducto_Result>("SP_Admin_EliminarImagenProducto", idImagenParameter);
        }
    
        public virtual ObjectResult<SP_Admin_InsertarCategoria_Result> SP_Admin_InsertarCategoria(string nombreCategoria, string descripcion)
        {
            var nombreCategoriaParameter = nombreCategoria != null ?
                new ObjectParameter("NombreCategoria", nombreCategoria) :
                new ObjectParameter("NombreCategoria", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Admin_InsertarCategoria_Result>("SP_Admin_InsertarCategoria", nombreCategoriaParameter, descripcionParameter);
        }
    
        public virtual ObjectResult<SP_Admin_InsertarImagenProducto_Result> SP_Admin_InsertarImagenProducto(Nullable<int> idProducto, string rutaImagen)
        {
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("IdProducto", idProducto) :
                new ObjectParameter("IdProducto", typeof(int));
    
            var rutaImagenParameter = rutaImagen != null ?
                new ObjectParameter("RutaImagen", rutaImagen) :
                new ObjectParameter("RutaImagen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Admin_InsertarImagenProducto_Result>("SP_Admin_InsertarImagenProducto", idProductoParameter, rutaImagenParameter);
        }
    
        public virtual ObjectResult<SP_Admin_InsertarProducto_Result> SP_Admin_InsertarProducto(string nombreProducto, string descripcion, Nullable<decimal> precio, Nullable<int> stock, Nullable<bool> esPiezaUnica, Nullable<bool> destacado, Nullable<int> idCategoria)
        {
            var nombreProductoParameter = nombreProducto != null ?
                new ObjectParameter("NombreProducto", nombreProducto) :
                new ObjectParameter("NombreProducto", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("Precio", precio) :
                new ObjectParameter("Precio", typeof(decimal));
    
            var stockParameter = stock.HasValue ?
                new ObjectParameter("Stock", stock) :
                new ObjectParameter("Stock", typeof(int));
    
            var esPiezaUnicaParameter = esPiezaUnica.HasValue ?
                new ObjectParameter("EsPiezaUnica", esPiezaUnica) :
                new ObjectParameter("EsPiezaUnica", typeof(bool));
    
            var destacadoParameter = destacado.HasValue ?
                new ObjectParameter("Destacado", destacado) :
                new ObjectParameter("Destacado", typeof(bool));
    
            var idCategoriaParameter = idCategoria.HasValue ?
                new ObjectParameter("IdCategoria", idCategoria) :
                new ObjectParameter("IdCategoria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Admin_InsertarProducto_Result>("SP_Admin_InsertarProducto", nombreProductoParameter, descripcionParameter, precioParameter, stockParameter, esPiezaUnicaParameter, destacadoParameter, idCategoriaParameter);
        }
    
        public virtual ObjectResult<SP_Admin_MarcarImagenPrincipal_Result> SP_Admin_MarcarImagenPrincipal(Nullable<int> idImagen)
        {
            var idImagenParameter = idImagen.HasValue ?
                new ObjectParameter("IdImagen", idImagen) :
                new ObjectParameter("IdImagen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Admin_MarcarImagenPrincipal_Result>("SP_Admin_MarcarImagenPrincipal", idImagenParameter);
        }
    
        public virtual ObjectResult<SP_Admin_ReporteProductosMasVendidos_Result> SP_Admin_ReporteProductosMasVendidos(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, Nullable<int> top)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var topParameter = top.HasValue ?
                new ObjectParameter("Top", top) :
                new ObjectParameter("Top", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Admin_ReporteProductosMasVendidos_Result>("SP_Admin_ReporteProductosMasVendidos", fechaInicioParameter, fechaFinParameter, topParameter);
        }
    
        public virtual ObjectResult<SP_Admin_ReporteResumenVentas_Result> SP_Admin_ReporteResumenVentas(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Admin_ReporteResumenVentas_Result>("SP_Admin_ReporteResumenVentas", fechaInicioParameter, fechaFinParameter);
        }
    
        public virtual ObjectResult<SP_Admin_ReporteVentasPorDia_Result> SP_Admin_ReporteVentasPorDia(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Admin_ReporteVentasPorDia_Result>("SP_Admin_ReporteVentasPorDia", fechaInicioParameter, fechaFinParameter);
        }
    
        public virtual ObjectResult<SP_AgregarProductoCarrito_Result> SP_AgregarProductoCarrito(Nullable<int> idUsuario, Nullable<int> idProducto, Nullable<int> cantidad)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("IdProducto", idProducto) :
                new ObjectParameter("IdProducto", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("Cantidad", cantidad) :
                new ObjectParameter("Cantidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_AgregarProductoCarrito_Result>("SP_AgregarProductoCarrito", idUsuarioParameter, idProductoParameter, cantidadParameter);
        }
    
        public virtual ObjectResult<SP_ConfirmarCompra_Result> SP_ConfirmarCompra(Nullable<int> idUsuario, Nullable<int> idDireccion, Nullable<int> idMetodoPago, Nullable<decimal> costoEnvio)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var idDireccionParameter = idDireccion.HasValue ?
                new ObjectParameter("IdDireccion", idDireccion) :
                new ObjectParameter("IdDireccion", typeof(int));
    
            var idMetodoPagoParameter = idMetodoPago.HasValue ?
                new ObjectParameter("IdMetodoPago", idMetodoPago) :
                new ObjectParameter("IdMetodoPago", typeof(int));
    
            var costoEnvioParameter = costoEnvio.HasValue ?
                new ObjectParameter("CostoEnvio", costoEnvio) :
                new ObjectParameter("CostoEnvio", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConfirmarCompra_Result>("SP_ConfirmarCompra", idUsuarioParameter, idDireccionParameter, idMetodoPagoParameter, costoEnvioParameter);
        }
    
        public virtual ObjectResult<SP_ConsultarCantonesPorProvincia_Result> SP_ConsultarCantonesPorProvincia(Nullable<int> idProvincia)
        {
            var idProvinciaParameter = idProvincia.HasValue ?
                new ObjectParameter("IdProvincia", idProvincia) :
                new ObjectParameter("IdProvincia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsultarCantonesPorProvincia_Result>("SP_ConsultarCantonesPorProvincia", idProvinciaParameter);
        }
    
        public virtual ObjectResult<SP_ConsultarCarrito_Result> SP_ConsultarCarrito(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsultarCarrito_Result>("SP_ConsultarCarrito", idUsuarioParameter);
        }
    
        public virtual ObjectResult<SP_ConsultarConfirmacionPedido_Result> SP_ConsultarConfirmacionPedido(Nullable<int> idPedido, Nullable<int> idUsuario)
        {
            var idPedidoParameter = idPedido.HasValue ?
                new ObjectParameter("IdPedido", idPedido) :
                new ObjectParameter("IdPedido", typeof(int));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsultarConfirmacionPedido_Result>("SP_ConsultarConfirmacionPedido", idPedidoParameter, idUsuarioParameter);
        }
    
        public virtual ObjectResult<SP_ConsultarDetallePedido_Result> SP_ConsultarDetallePedido(Nullable<int> idPedido, Nullable<int> idUsuario)
        {
            var idPedidoParameter = idPedido.HasValue ?
                new ObjectParameter("IdPedido", idPedido) :
                new ObjectParameter("IdPedido", typeof(int));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsultarDetallePedido_Result>("SP_ConsultarDetallePedido", idPedidoParameter, idUsuarioParameter);
        }
    
        public virtual ObjectResult<SP_ConsultarDireccionesUsuario_Result> SP_ConsultarDireccionesUsuario(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsultarDireccionesUsuario_Result>("SP_ConsultarDireccionesUsuario", idUsuarioParameter);
        }
    
        public virtual ObjectResult<SP_ConsultarDireccionPorId_Result> SP_ConsultarDireccionPorId(Nullable<int> idDireccion, Nullable<int> idUsuario)
        {
            var idDireccionParameter = idDireccion.HasValue ?
                new ObjectParameter("IdDireccion", idDireccion) :
                new ObjectParameter("IdDireccion", typeof(int));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsultarDireccionPorId_Result>("SP_ConsultarDireccionPorId", idDireccionParameter, idUsuarioParameter);
        }
    
        public virtual ObjectResult<SP_ConsultarDistritosPorCanton_Result> SP_ConsultarDistritosPorCanton(Nullable<int> idCanton)
        {
            var idCantonParameter = idCanton.HasValue ?
                new ObjectParameter("IdCanton", idCanton) :
                new ObjectParameter("IdCanton", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsultarDistritosPorCanton_Result>("SP_ConsultarDistritosPorCanton", idCantonParameter);
        }
    
        public virtual ObjectResult<SP_ConsultarEstados_Result> SP_ConsultarEstados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsultarEstados_Result>("SP_ConsultarEstados");
        }
    
        public virtual ObjectResult<SP_ConsultarEstadosUsuario_Result> SP_ConsultarEstadosUsuario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsultarEstadosUsuario_Result>("SP_ConsultarEstadosUsuario");
        }
    
        public virtual ObjectResult<SP_ConsultarHistorialPedidos_Result> SP_ConsultarHistorialPedidos(Nullable<int> idUsuario, Nullable<int> pagina, Nullable<int> tamanoPagina)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var paginaParameter = pagina.HasValue ?
                new ObjectParameter("Pagina", pagina) :
                new ObjectParameter("Pagina", typeof(int));
    
            var tamanoPaginaParameter = tamanoPagina.HasValue ?
                new ObjectParameter("TamanoPagina", tamanoPagina) :
                new ObjectParameter("TamanoPagina", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsultarHistorialPedidos_Result>("SP_ConsultarHistorialPedidos", idUsuarioParameter, paginaParameter, tamanoPaginaParameter);
        }
    
        public virtual ObjectResult<SP_ConsultarMetodosPago_Result> SP_ConsultarMetodosPago()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsultarMetodosPago_Result>("SP_ConsultarMetodosPago");
        }
    
        public virtual ObjectResult<SP_ConsultarProvincias_Result> SP_ConsultarProvincias()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsultarProvincias_Result>("SP_ConsultarProvincias");
        }
    
        public virtual ObjectResult<SP_ConsultarResumenCheckout_Result> SP_ConsultarResumenCheckout(Nullable<int> idUsuario, Nullable<int> idDireccion)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var idDireccionParameter = idDireccion.HasValue ?
                new ObjectParameter("IdDireccion", idDireccion) :
                new ObjectParameter("IdDireccion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsultarResumenCheckout_Result>("SP_ConsultarResumenCheckout", idUsuarioParameter, idDireccionParameter);
        }
    
        public virtual ObjectResult<SP_ConsultarRoles_Result> SP_ConsultarRoles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsultarRoles_Result>("SP_ConsultarRoles");
        }
    
        public virtual ObjectResult<SP_ConsultarUsuarioInicioSesion_Result> SP_ConsultarUsuarioInicioSesion(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsultarUsuarioInicioSesion_Result>("SP_ConsultarUsuarioInicioSesion", emailParameter);
        }
    
        public virtual ObjectResult<SP_ConsultarUsuarioPorId_Result> SP_ConsultarUsuarioPorId(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsultarUsuarioPorId_Result>("SP_ConsultarUsuarioPorId", idUsuarioParameter);
        }
    
        public virtual ObjectResult<SP_ConsultarUsuarioRecuperacion_Result> SP_ConsultarUsuarioRecuperacion(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsultarUsuarioRecuperacion_Result>("SP_ConsultarUsuarioRecuperacion", emailParameter);
        }
    
        public virtual ObjectResult<SP_ConsultarUsuarios_Result> SP_ConsultarUsuarios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsultarUsuarios_Result>("SP_ConsultarUsuarios");
        }
    
        public virtual ObjectResult<SP_Dashboard_ConsultarActividadReciente_Result> SP_Dashboard_ConsultarActividadReciente(Nullable<int> cantidad)
        {
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("Cantidad", cantidad) :
                new ObjectParameter("Cantidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Dashboard_ConsultarActividadReciente_Result>("SP_Dashboard_ConsultarActividadReciente", cantidadParameter);
        }
    
        public virtual ObjectResult<SP_Dashboard_ConsultarResumen_Result> SP_Dashboard_ConsultarResumen()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Dashboard_ConsultarResumen_Result>("SP_Dashboard_ConsultarResumen");
        }
    
        public virtual ObjectResult<SP_Dashboard_ConsultarVentasMensuales_Result> SP_Dashboard_ConsultarVentasMensuales(Nullable<int> anno)
        {
            var annoParameter = anno.HasValue ?
                new ObjectParameter("Anno", anno) :
                new ObjectParameter("Anno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Dashboard_ConsultarVentasMensuales_Result>("SP_Dashboard_ConsultarVentasMensuales", annoParameter);
        }
    
        public virtual ObjectResult<SP_DesactivarDireccionUsuario_Result> SP_DesactivarDireccionUsuario(Nullable<int> idDireccion, Nullable<int> idUsuario)
        {
            var idDireccionParameter = idDireccion.HasValue ?
                new ObjectParameter("IdDireccion", idDireccion) :
                new ObjectParameter("IdDireccion", typeof(int));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DesactivarDireccionUsuario_Result>("SP_DesactivarDireccionUsuario", idDireccionParameter, idUsuarioParameter);
        }
    
        public virtual ObjectResult<SP_EliminarProductoCarrito_Result> SP_EliminarProductoCarrito(Nullable<int> idUsuario, Nullable<int> idProducto)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("IdProducto", idProducto) :
                new ObjectParameter("IdProducto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_EliminarProductoCarrito_Result>("SP_EliminarProductoCarrito", idUsuarioParameter, idProductoParameter);
        }
    
        public virtual ObjectResult<SP_InsertarDireccionUsuario_Result> SP_InsertarDireccionUsuario(Nullable<int> idUsuario, Nullable<int> idDistrito, string direccionExacta, string referencia, string telefonoContacto, string nombreDestinatario, Nullable<bool> esPrincipal)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var idDistritoParameter = idDistrito.HasValue ?
                new ObjectParameter("IdDistrito", idDistrito) :
                new ObjectParameter("IdDistrito", typeof(int));
    
            var direccionExactaParameter = direccionExacta != null ?
                new ObjectParameter("DireccionExacta", direccionExacta) :
                new ObjectParameter("DireccionExacta", typeof(string));
    
            var referenciaParameter = referencia != null ?
                new ObjectParameter("Referencia", referencia) :
                new ObjectParameter("Referencia", typeof(string));
    
            var telefonoContactoParameter = telefonoContacto != null ?
                new ObjectParameter("TelefonoContacto", telefonoContacto) :
                new ObjectParameter("TelefonoContacto", typeof(string));
    
            var nombreDestinatarioParameter = nombreDestinatario != null ?
                new ObjectParameter("NombreDestinatario", nombreDestinatario) :
                new ObjectParameter("NombreDestinatario", typeof(string));
    
            var esPrincipalParameter = esPrincipal.HasValue ?
                new ObjectParameter("EsPrincipal", esPrincipal) :
                new ObjectParameter("EsPrincipal", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_InsertarDireccionUsuario_Result>("SP_InsertarDireccionUsuario", idUsuarioParameter, idDistritoParameter, direccionExactaParameter, referenciaParameter, telefonoContactoParameter, nombreDestinatarioParameter, esPrincipalParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_ObtenerOCrearCarritoActivo(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_ObtenerOCrearCarritoActivo", idUsuarioParameter);
        }
    
        public virtual int SP_RegistrarError(string origen, string metodo, string mensajeError, string detalleError, Nullable<int> lineaError, string usuarioSistema, string url, string stackTrace)
        {
            var origenParameter = origen != null ?
                new ObjectParameter("Origen", origen) :
                new ObjectParameter("Origen", typeof(string));
    
            var metodoParameter = metodo != null ?
                new ObjectParameter("Metodo", metodo) :
                new ObjectParameter("Metodo", typeof(string));
    
            var mensajeErrorParameter = mensajeError != null ?
                new ObjectParameter("MensajeError", mensajeError) :
                new ObjectParameter("MensajeError", typeof(string));
    
            var detalleErrorParameter = detalleError != null ?
                new ObjectParameter("DetalleError", detalleError) :
                new ObjectParameter("DetalleError", typeof(string));
    
            var lineaErrorParameter = lineaError.HasValue ?
                new ObjectParameter("LineaError", lineaError) :
                new ObjectParameter("LineaError", typeof(int));
    
            var usuarioSistemaParameter = usuarioSistema != null ?
                new ObjectParameter("UsuarioSistema", usuarioSistema) :
                new ObjectParameter("UsuarioSistema", typeof(string));
    
            var urlParameter = url != null ?
                new ObjectParameter("Url", url) :
                new ObjectParameter("Url", typeof(string));
    
            var stackTraceParameter = stackTrace != null ?
                new ObjectParameter("StackTrace", stackTrace) :
                new ObjectParameter("StackTrace", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_RegistrarError", origenParameter, metodoParameter, mensajeErrorParameter, detalleErrorParameter, lineaErrorParameter, usuarioSistemaParameter, urlParameter, stackTraceParameter);
        }
    
        public virtual ObjectResult<SP_RegistrarUsuario_Result> SP_RegistrarUsuario(string nombre, string apellido, string cedula, string telefono, string email, string contrasenna)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var contrasennaParameter = contrasenna != null ?
                new ObjectParameter("Contrasenna", contrasenna) :
                new ObjectParameter("Contrasenna", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_RegistrarUsuario_Result>("SP_RegistrarUsuario", nombreParameter, apellidoParameter, cedulaParameter, telefonoParameter, emailParameter, contrasennaParameter);
        }
    
        public virtual ObjectResult<SP_RegistrarUsuarioAdministracion_Result> SP_RegistrarUsuarioAdministracion(string nombre, string apellido, string cedula, string telefono, string email, string contrasenna, Nullable<int> idRol, Nullable<int> idEstado)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var contrasennaParameter = contrasenna != null ?
                new ObjectParameter("Contrasenna", contrasenna) :
                new ObjectParameter("Contrasenna", typeof(string));
    
            var idRolParameter = idRol.HasValue ?
                new ObjectParameter("IdRol", idRol) :
                new ObjectParameter("IdRol", typeof(int));
    
            var idEstadoParameter = idEstado.HasValue ?
                new ObjectParameter("IdEstado", idEstado) :
                new ObjectParameter("IdEstado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_RegistrarUsuarioAdministracion_Result>("SP_RegistrarUsuarioAdministracion", nombreParameter, apellidoParameter, cedulaParameter, telefonoParameter, emailParameter, contrasennaParameter, idRolParameter, idEstadoParameter);
        }
    
        public virtual ObjectResult<SP_RestablecerContrasennaUsuario_Result> SP_RestablecerContrasennaUsuario(Nullable<int> idUsuario, string contrasenna)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var contrasennaParameter = contrasenna != null ?
                new ObjectParameter("Contrasenna", contrasenna) :
                new ObjectParameter("Contrasenna", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_RestablecerContrasennaUsuario_Result>("SP_RestablecerContrasennaUsuario", idUsuarioParameter, contrasennaParameter);
        }
    }
}
