//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacionAvanzada.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BD_LENEntities : DbContext
    {
        public BD_LENEntities()
            : base("name=BD_LENEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_canton> TB_canton { get; set; }
        public virtual DbSet<TB_carrito> TB_carrito { get; set; }
        public virtual DbSet<TB_categoria> TB_categoria { get; set; }
        public virtual DbSet<TB_detalle_carrito> TB_detalle_carrito { get; set; }
        public virtual DbSet<TB_detalle_pedido> TB_detalle_pedido { get; set; }
        public virtual DbSet<TB_direccion_envio> TB_direccion_envio { get; set; }
        public virtual DbSet<TB_distrito> TB_distrito { get; set; }
        public virtual DbSet<TB_error> TB_error { get; set; }
        public virtual DbSet<TB_estado> TB_estado { get; set; }
        public virtual DbSet<TB_factura> TB_factura { get; set; }
        public virtual DbSet<TB_imagen_producto> TB_imagen_producto { get; set; }
        public virtual DbSet<TB_metodo_pago> TB_metodo_pago { get; set; }
        public virtual DbSet<TB_pago> TB_pago { get; set; }
        public virtual DbSet<TB_pedido> TB_pedido { get; set; }
        public virtual DbSet<TB_producto> TB_producto { get; set; }
        public virtual DbSet<TB_provincia> TB_provincia { get; set; }
        public virtual DbSet<TB_rol> TB_rol { get; set; }
        public virtual DbSet<TB_usuario> TB_usuario { get; set; }
    
        public virtual ObjectResult<SP_ConsultarUsuarioInicioSesion_Result> SP_ConsultarUsuarioInicioSesion(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsultarUsuarioInicioSesion_Result>("SP_ConsultarUsuarioInicioSesion", emailParameter);
        }
    
        public virtual int SP_RegistrarError(string origen, string metodo, string mensajeError, string detalleError, Nullable<int> lineaError, string usuarioSistema, string url, string stackTrace)
        {
            var origenParameter = origen != null ?
                new ObjectParameter("Origen", origen) :
                new ObjectParameter("Origen", typeof(string));
    
            var metodoParameter = metodo != null ?
                new ObjectParameter("Metodo", metodo) :
                new ObjectParameter("Metodo", typeof(string));
    
            var mensajeErrorParameter = mensajeError != null ?
                new ObjectParameter("MensajeError", mensajeError) :
                new ObjectParameter("MensajeError", typeof(string));
    
            var detalleErrorParameter = detalleError != null ?
                new ObjectParameter("DetalleError", detalleError) :
                new ObjectParameter("DetalleError", typeof(string));
    
            var lineaErrorParameter = lineaError.HasValue ?
                new ObjectParameter("LineaError", lineaError) :
                new ObjectParameter("LineaError", typeof(int));
    
            var usuarioSistemaParameter = usuarioSistema != null ?
                new ObjectParameter("UsuarioSistema", usuarioSistema) :
                new ObjectParameter("UsuarioSistema", typeof(string));
    
            var urlParameter = url != null ?
                new ObjectParameter("Url", url) :
                new ObjectParameter("Url", typeof(string));
    
            var stackTraceParameter = stackTrace != null ?
                new ObjectParameter("StackTrace", stackTrace) :
                new ObjectParameter("StackTrace", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_RegistrarError", origenParameter, metodoParameter, mensajeErrorParameter, detalleErrorParameter, lineaErrorParameter, usuarioSistemaParameter, urlParameter, stackTraceParameter);
        }
    
        public virtual ObjectResult<SP_ActualizarDireccionUsuario_Result> SP_ActualizarDireccionUsuario(Nullable<int> idDireccion, Nullable<int> idUsuario, Nullable<int> idDistrito, string direccionExacta, string referencia, string telefonoContacto, string nombreDestinatario, Nullable<bool> esPrincipal)
        {
            var idDireccionParameter = idDireccion.HasValue ?
                new ObjectParameter("IdDireccion", idDireccion) :
                new ObjectParameter("IdDireccion", typeof(int));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var idDistritoParameter = idDistrito.HasValue ?
                new ObjectParameter("IdDistrito", idDistrito) :
                new ObjectParameter("IdDistrito", typeof(int));
    
            var direccionExactaParameter = direccionExacta != null ?
                new ObjectParameter("DireccionExacta", direccionExacta) :
                new ObjectParameter("DireccionExacta", typeof(string));
    
            var referenciaParameter = referencia != null ?
                new ObjectParameter("Referencia", referencia) :
                new ObjectParameter("Referencia", typeof(string));
    
            var telefonoContactoParameter = telefonoContacto != null ?
                new ObjectParameter("TelefonoContacto", telefonoContacto) :
                new ObjectParameter("TelefonoContacto", typeof(string));
    
            var nombreDestinatarioParameter = nombreDestinatario != null ?
                new ObjectParameter("NombreDestinatario", nombreDestinatario) :
                new ObjectParameter("NombreDestinatario", typeof(string));
    
            var esPrincipalParameter = esPrincipal.HasValue ?
                new ObjectParameter("EsPrincipal", esPrincipal) :
                new ObjectParameter("EsPrincipal", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ActualizarDireccionUsuario_Result>("SP_ActualizarDireccionUsuario", idDireccionParameter, idUsuarioParameter, idDistritoParameter, direccionExactaParameter, referenciaParameter, telefonoContactoParameter, nombreDestinatarioParameter, esPrincipalParameter);
        }
    
        public virtual ObjectResult<SP_ActualizarUsuario_Result> SP_ActualizarUsuario(Nullable<int> idUsuario, string nombre, string apellido, string cedula, string telefono, string email, Nullable<int> idRol, Nullable<int> idEstado)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var idRolParameter = idRol.HasValue ?
                new ObjectParameter("IdRol", idRol) :
                new ObjectParameter("IdRol", typeof(int));
    
            var idEstadoParameter = idEstado.HasValue ?
                new ObjectParameter("IdEstado", idEstado) :
                new ObjectParameter("IdEstado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ActualizarUsuario_Result>("SP_ActualizarUsuario", idUsuarioParameter, nombreParameter, apellidoParameter, cedulaParameter, telefonoParameter, emailParameter, idRolParameter, idEstadoParameter);
        }
    
        public virtual ObjectResult<SP_ConsultarCantonesPorProvincia_Result> SP_ConsultarCantonesPorProvincia(Nullable<int> idProvincia)
        {
            var idProvinciaParameter = idProvincia.HasValue ?
                new ObjectParameter("IdProvincia", idProvincia) :
                new ObjectParameter("IdProvincia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsultarCantonesPorProvincia_Result>("SP_ConsultarCantonesPorProvincia", idProvinciaParameter);
        }
    
        public virtual ObjectResult<SP_ConsultarDireccionesUsuario_Result> SP_ConsultarDireccionesUsuario(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsultarDireccionesUsuario_Result>("SP_ConsultarDireccionesUsuario", idUsuarioParameter);
        }
    
        public virtual ObjectResult<SP_ConsultarDireccionPorId_Result> SP_ConsultarDireccionPorId(Nullable<int> idDireccion, Nullable<int> idUsuario)
        {
            var idDireccionParameter = idDireccion.HasValue ?
                new ObjectParameter("IdDireccion", idDireccion) :
                new ObjectParameter("IdDireccion", typeof(int));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsultarDireccionPorId_Result>("SP_ConsultarDireccionPorId", idDireccionParameter, idUsuarioParameter);
        }
    
        public virtual ObjectResult<SP_ConsultarDistritosPorCanton_Result> SP_ConsultarDistritosPorCanton(Nullable<int> idCanton)
        {
            var idCantonParameter = idCanton.HasValue ?
                new ObjectParameter("IdCanton", idCanton) :
                new ObjectParameter("IdCanton", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsultarDistritosPorCanton_Result>("SP_ConsultarDistritosPorCanton", idCantonParameter);
        }
    
        public virtual ObjectResult<SP_ConsultarEstados_Result> SP_ConsultarEstados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsultarEstados_Result>("SP_ConsultarEstados");
        }
    
        public virtual ObjectResult<SP_ConsultarProvincias_Result> SP_ConsultarProvincias()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsultarProvincias_Result>("SP_ConsultarProvincias");
        }
    
        public virtual ObjectResult<SP_ConsultarRoles_Result> SP_ConsultarRoles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsultarRoles_Result>("SP_ConsultarRoles");
        }
    
        public virtual ObjectResult<SP_ConsultarUsuarioPorId_Result> SP_ConsultarUsuarioPorId(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsultarUsuarioPorId_Result>("SP_ConsultarUsuarioPorId", idUsuarioParameter);
        }
    
        public virtual ObjectResult<SP_DesactivarDireccionUsuario_Result> SP_DesactivarDireccionUsuario(Nullable<int> idDireccion, Nullable<int> idUsuario)
        {
            var idDireccionParameter = idDireccion.HasValue ?
                new ObjectParameter("IdDireccion", idDireccion) :
                new ObjectParameter("IdDireccion", typeof(int));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DesactivarDireccionUsuario_Result>("SP_DesactivarDireccionUsuario", idDireccionParameter, idUsuarioParameter);
        }
    
        public virtual ObjectResult<SP_InsertarDireccionUsuario_Result> SP_InsertarDireccionUsuario(Nullable<int> idUsuario, Nullable<int> idDistrito, string direccionExacta, string referencia, string telefonoContacto, string nombreDestinatario, Nullable<bool> esPrincipal)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var idDistritoParameter = idDistrito.HasValue ?
                new ObjectParameter("IdDistrito", idDistrito) :
                new ObjectParameter("IdDistrito", typeof(int));
    
            var direccionExactaParameter = direccionExacta != null ?
                new ObjectParameter("DireccionExacta", direccionExacta) :
                new ObjectParameter("DireccionExacta", typeof(string));
    
            var referenciaParameter = referencia != null ?
                new ObjectParameter("Referencia", referencia) :
                new ObjectParameter("Referencia", typeof(string));
    
            var telefonoContactoParameter = telefonoContacto != null ?
                new ObjectParameter("TelefonoContacto", telefonoContacto) :
                new ObjectParameter("TelefonoContacto", typeof(string));
    
            var nombreDestinatarioParameter = nombreDestinatario != null ?
                new ObjectParameter("NombreDestinatario", nombreDestinatario) :
                new ObjectParameter("NombreDestinatario", typeof(string));
    
            var esPrincipalParameter = esPrincipal.HasValue ?
                new ObjectParameter("EsPrincipal", esPrincipal) :
                new ObjectParameter("EsPrincipal", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_InsertarDireccionUsuario_Result>("SP_InsertarDireccionUsuario", idUsuarioParameter, idDistritoParameter, direccionExactaParameter, referenciaParameter, telefonoContactoParameter, nombreDestinatarioParameter, esPrincipalParameter);
        }
    
        public virtual ObjectResult<SP_RestablecerContrasennaUsuario_Result> SP_RestablecerContrasennaUsuario(Nullable<int> idUsuario, string contrasenna)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var contrasennaParameter = contrasenna != null ?
                new ObjectParameter("Contrasenna", contrasenna) :
                new ObjectParameter("Contrasenna", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_RestablecerContrasennaUsuario_Result>("SP_RestablecerContrasennaUsuario", idUsuarioParameter, contrasennaParameter);
        }
    
        public virtual ObjectResult<SP_ConsultarEstadosUsuario_Result> SP_ConsultarEstadosUsuario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsultarEstadosUsuario_Result>("SP_ConsultarEstadosUsuario");
        }
    }
}
