//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacionAvanzada.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BD_LENEntities : DbContext
    {
        public BD_LENEntities()
            : base("name=BD_LENEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_canton> TB_canton { get; set; }
        public virtual DbSet<TB_carrito> TB_carrito { get; set; }
        public virtual DbSet<TB_categoria> TB_categoria { get; set; }
        public virtual DbSet<TB_detalle_carrito> TB_detalle_carrito { get; set; }
        public virtual DbSet<TB_detalle_pedido> TB_detalle_pedido { get; set; }
        public virtual DbSet<TB_direccion_envio> TB_direccion_envio { get; set; }
        public virtual DbSet<TB_distrito> TB_distrito { get; set; }
        public virtual DbSet<TB_error> TB_error { get; set; }
        public virtual DbSet<TB_estado> TB_estado { get; set; }
        public virtual DbSet<TB_factura> TB_factura { get; set; }
        public virtual DbSet<TB_imagen_producto> TB_imagen_producto { get; set; }
        public virtual DbSet<TB_metodo_pago> TB_metodo_pago { get; set; }
        public virtual DbSet<TB_pago> TB_pago { get; set; }
        public virtual DbSet<TB_pedido> TB_pedido { get; set; }
        public virtual DbSet<TB_producto> TB_producto { get; set; }
        public virtual DbSet<TB_provincia> TB_provincia { get; set; }
        public virtual DbSet<TB_rol> TB_rol { get; set; }
        public virtual DbSet<TB_usuario> TB_usuario { get; set; }
    
        public virtual ObjectResult<SP_ConsultarUsuarioInicioSesion_Result> SP_ConsultarUsuarioInicioSesion(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsultarUsuarioInicioSesion_Result>("SP_ConsultarUsuarioInicioSesion", emailParameter);
        }
    
        public virtual int SP_RegistrarError(string origen, string metodo, string mensajeError, string detalleError, Nullable<int> lineaError, string usuarioSistema, string url, string stackTrace)
        {
            var origenParameter = origen != null ?
                new ObjectParameter("Origen", origen) :
                new ObjectParameter("Origen", typeof(string));
    
            var metodoParameter = metodo != null ?
                new ObjectParameter("Metodo", metodo) :
                new ObjectParameter("Metodo", typeof(string));
    
            var mensajeErrorParameter = mensajeError != null ?
                new ObjectParameter("MensajeError", mensajeError) :
                new ObjectParameter("MensajeError", typeof(string));
    
            var detalleErrorParameter = detalleError != null ?
                new ObjectParameter("DetalleError", detalleError) :
                new ObjectParameter("DetalleError", typeof(string));
    
            var lineaErrorParameter = lineaError.HasValue ?
                new ObjectParameter("LineaError", lineaError) :
                new ObjectParameter("LineaError", typeof(int));
    
            var usuarioSistemaParameter = usuarioSistema != null ?
                new ObjectParameter("UsuarioSistema", usuarioSistema) :
                new ObjectParameter("UsuarioSistema", typeof(string));
    
            var urlParameter = url != null ?
                new ObjectParameter("Url", url) :
                new ObjectParameter("Url", typeof(string));
    
            var stackTraceParameter = stackTrace != null ?
                new ObjectParameter("StackTrace", stackTrace) :
                new ObjectParameter("StackTrace", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_RegistrarError", origenParameter, metodoParameter, mensajeErrorParameter, detalleErrorParameter, lineaErrorParameter, usuarioSistemaParameter, urlParameter, stackTraceParameter);
        }
    }
}
