//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacionAvanzada.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_carrito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_carrito()
        {
            this.TB_detalle_carrito = new HashSet<TB_detalle_carrito>();
        }
    
        public int id_carrito { get; set; }
        public int id_usuario { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public int id_estado { get; set; }
    
        public virtual TB_estado TB_estado { get; set; }
        public virtual TB_usuario TB_usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_detalle_carrito> TB_detalle_carrito { get; set; }
    }
}
