//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacionAvanzada.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_direccion_envio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_direccion_envio()
        {
            this.TB_pedido = new HashSet<TB_pedido>();
        }
    
        public int id_direccion { get; set; }
        public int id_usuario { get; set; }
        public int id_distrito { get; set; }
        public string direccion_exacta { get; set; }
        public string referencia { get; set; }
        public string telefono_contacto { get; set; }
        public string nombre_destinatario { get; set; }
        public bool es_principal { get; set; }
        public int id_estado { get; set; }
    
        public virtual TB_distrito TB_distrito { get; set; }
        public virtual TB_estado TB_estado { get; set; }
        public virtual TB_usuario TB_usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_pedido> TB_pedido { get; set; }
    }
}
