//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacionAvanzada.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_detalle_carrito
    {
        public int id_detalle_carrito { get; set; }
        public int id_carrito { get; set; }
        public int id_producto { get; set; }
        public int cantidad { get; set; }
    
        public virtual TB_carrito TB_carrito { get; set; }
        public virtual TB_producto TB_producto { get; set; }
    }
}
