//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacionAvanzada.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_error
    {
        public int id_error { get; set; }
        public System.DateTime fecha_error { get; set; }
        public string origen { get; set; }
        public string metodo { get; set; }
        public string mensaje_error { get; set; }
        public string detalle_error { get; set; }
        public Nullable<int> linea_error { get; set; }
        public string usuario_sistema { get; set; }
        public string url { get; set; }
        public string stack_trace { get; set; }
    }
}
