//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacionAvanzada.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_error
    {
        public int id_error { get; set; }
        public System.DateTime fecha_error { get; set; }
        public string origen { get; set; }
        public string metodo { get; set; }
        public string mensaje_error { get; set; }
        public string detalle_error { get; set; }
        public Nullable<int> linea_error { get; set; }
        public string usuario_sistema { get; set; }
        public string url { get; set; }
        public string stack_trace { get; set; }
    }
}
