//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacionAvanzada.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_factura
    {
        public int id_factura { get; set; }
        public int id_pedido { get; set; }
        public string numero_factura { get; set; }
        public System.DateTime fecha_factura { get; set; }
        public decimal subtotal { get; set; }
        public decimal costo_envio { get; set; }
        public decimal total { get; set; }
        public int id_estado { get; set; }
    
        public virtual TB_estado TB_estado { get; set; }
        public virtual TB_pedido TB_pedido { get; set; }
    }
}
