//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacionAvanzada.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_factura
    {
        public int id_factura { get; set; }
        public int id_pedido { get; set; }
        public string numero_factura { get; set; }
        public System.DateTime fecha_factura { get; set; }
        public decimal subtotal { get; set; }
        public decimal costo_envio { get; set; }
        public decimal total { get; set; }
        public int id_estado { get; set; }
    
        public virtual TB_estado TB_estado { get; set; }
        public virtual TB_pedido TB_pedido { get; set; }
    }
}
