//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacionAvanzada.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_imagen_producto
    {
        public int id_imagen { get; set; }
        public int id_producto { get; set; }
        public string ruta_imagen { get; set; }
        public bool es_principal { get; set; }
        public int id_estado { get; set; }
    
        public virtual TB_estado TB_estado { get; set; }
        public virtual TB_producto TB_producto { get; set; }
    }
}
