//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacionAvanzada.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_pago
    {
        public int id_pago { get; set; }
        public int id_pedido { get; set; }
        public int id_metodo_pago { get; set; }
        public decimal monto { get; set; }
        public System.DateTime fecha_pago { get; set; }
        public string comprobante { get; set; }
        public int id_estado { get; set; }
    
        public virtual TB_estado TB_estado { get; set; }
        public virtual TB_metodo_pago TB_metodo_pago { get; set; }
        public virtual TB_pedido TB_pedido { get; set; }
    }
}
