//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacionAvanzada.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_pago
    {
        public int id_pago { get; set; }
        public int id_pedido { get; set; }
        public int id_metodo_pago { get; set; }
        public decimal monto { get; set; }
        public System.DateTime fecha_pago { get; set; }
        public string comprobante { get; set; }
        public int id_estado { get; set; }
    
        public virtual TB_estado TB_estado { get; set; }
        public virtual TB_metodo_pago TB_metodo_pago { get; set; }
        public virtual TB_pedido TB_pedido { get; set; }
    }
}
