//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacionAvanzada.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_producto()
        {
            this.TB_detalle_carrito = new HashSet<TB_detalle_carrito>();
            this.TB_detalle_pedido = new HashSet<TB_detalle_pedido>();
            this.TB_imagen_producto = new HashSet<TB_imagen_producto>();
        }
    
        public int id_producto { get; set; }
        public string nombre_producto { get; set; }
        public string descripcion { get; set; }
        public decimal precio { get; set; }
        public int stock { get; set; }
        public bool es_pieza_unica { get; set; }
        public bool destacado { get; set; }
        public int id_categoria { get; set; }
        public int id_estado { get; set; }
        public System.DateTime fecha_creacion { get; set; }
    
        public virtual TB_categoria TB_categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_detalle_carrito> TB_detalle_carrito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_detalle_pedido> TB_detalle_pedido { get; set; }
        public virtual TB_estado TB_estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_imagen_producto> TB_imagen_producto { get; set; }
    }
}
