//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacionAvanzada.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_pedido()
        {
            this.TB_detalle_pedido = new HashSet<TB_detalle_pedido>();
            this.TB_factura = new HashSet<TB_factura>();
            this.TB_pago = new HashSet<TB_pago>();
        }
    
        public int id_pedido { get; set; }
        public int id_usuario { get; set; }
        public int id_direccion { get; set; }
        public System.DateTime fecha_pedido { get; set; }
        public decimal subtotal { get; set; }
        public decimal costo_envio { get; set; }
        public decimal total { get; set; }
        public int id_estado { get; set; }
        public string motivo_cancelacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_detalle_pedido> TB_detalle_pedido { get; set; }
        public virtual TB_direccion_envio TB_direccion_envio { get; set; }
        public virtual TB_estado TB_estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_factura> TB_factura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_pago> TB_pago { get; set; }
        public virtual TB_usuario TB_usuario { get; set; }
    }
}
