//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacionAvanzada.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_variante_producto
    {
        public int id_variante { get; set; }
        public int id_producto { get; set; }
        public string color { get; set; }
        public string talla { get; set; }
        public string modelo { get; set; }
        public int stock { get; set; }
        public int id_estado { get; set; }
    
        public virtual TB_estado TB_estado { get; set; }
        public virtual TB_producto TB_producto { get; set; }
    }
}
